CREATE TABLE manifest_content (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
  manifest_id INTEGER UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  edition_date DATETIME NOT NULL,
  FOREIGN KEY (manifest_id)
    REFERENCES manifest(id)
    ON DELETE CASCADE
);
