language: node_js
node_js:
  - "8"
before_script:
  - cd server
  - npm i

script:
  - npm test

# Discord notifications
after_success:
  - wget https://gist.githubusercontent.com/Arignir/d9a8cb72c9a7c95b7981df56a188d5de/raw/3703660d851e81444c2ce26b3d41d98081e2f2c4/discord.sh
  - chmod +x discord.sh
  - ./discord.sh success "$DISCORD_WEBHOOK_URL"
after_failure:
  - wget https://gist.githubusercontent.com/Arignir/d9a8cb72c9a7c95b7981df56a188d5de/raw/3703660d851e81444c2ce26b3d41d98081e2f2c4/discord.sh
  - chmod +x discord.sh
  - ./discord.sh failure "$DISCORD_WEBHOOK_URL"
