// Manifests
export const MANIFEST_CREATE_REQUEST = 'MANIFEST_CREATE_REQUEST'
export const MANIFEST_CREATE_SUCCESS = 'MANIFEST_CREATE_SUCCESS'
export const MANIFEST_CREATE_ERROR = 'MANIFEST_CREATE_ERROR'

export const MANIFEST_UPDATE_REQUEST = 'MANIFEST_UPDATE_REQUEST'
export const MANIFEST_UPDATE_SUCCESS = 'MANIFEST_UPDATE_SUCCESS'
export const MANIFEST_UPDATE_ERROR = 'MANIFEST_UPDATE_ERROR'

export const MANIFEST_LIST_REQUEST = 'MANIFEST_LIST_REQUEST'
export const MANIFEST_LIST_SUCCESS = 'MANIFEST_LIST_SUCCESS'
export const MANIFEST_LIST_ERROR = 'MANIFEST_LIST_ERROR'

export const MANIFEST_GET_REQUEST = 'MANIFEST_GET_REQUEST'
export const MANIFEST_GET_SUCCESS = 'MANIFEST_GET_SUCCESS'
export const MANIFEST_GET_ERROR = 'MANIFEST_GET_ERROR'

// Builds
export const BUILD_CREATE_REQUEST = 'BUILD_CREATE_REQUEST'
export const BUILD_CREATE_SUCCESS = 'BUILD_CREATE_SUCCESS'
export const BUILD_CREATE_ERROR = 'BUILD_CREATE_ERROR'

export const BUILD_LIST_REQUEST = 'BUILD_LIST_REQUEST'
export const BUILD_LIST_SUCCESS = 'BUILD_LIST_SUCCESS'
export const BUILD_LIST_ERROR = 'BUILD_LIST_ERROR'

export const BUILD_GET_REQUEST = 'BUILD_GET_REQUEST'
export const BUILD_GET_SUCCESS = 'BUILD_GET_SUCCESS'
export const BUILD_GET_ERROR = 'BUILD_GET_ERROR'
