// Manifests
export const MANIFEST_CREATE_REQUEST = 'MANIFEST_CREATE_REQUEST'
export const MANIFEST_CREATE_SUCCESS = 'MANIFEST_CREATE_SUCCESS'
export const MANIFEST_CREATE_ERROR = 'MANIFEST_CREATE_ERROR'

export const MANIFEST_UPDATE_REQUEST = 'MANIFEST_UPDATE_REQUEST'
export const MANIFEST_UPDATE_SUCCESS = 'MANIFEST_UPDATE_SUCCESS'
export const MANIFEST_UPDATE_ERROR = 'MANIFEST_UPDATE_ERROR'

export const MANIFEST_LIST_REQUEST = 'MANIFEST_LIST_REQUEST'
export const MANIFEST_LIST_SUCCESS = 'MANIFEST_LIST_SUCCESS'
export const MANIFEST_LIST_ERROR = 'MANIFEST_LIST_ERROR'

export const MANIFEST_GET_REQUEST = 'MANIFEST_GET_REQUEST'
export const MANIFEST_GET_SUCCESS = 'MANIFEST_GET_SUCCESS'
export const MANIFEST_GET_ERROR = 'MANIFEST_GET_ERROR'

// Builds
export const BUILD_CREATE_REQUEST = 'BUILD_CREATE_REQUEST'
export const BUILD_CREATE_SUCCESS = 'BUILD_CREATE_SUCCESS'
export const BUILD_CREATE_ERROR = 'BUILD_CREATE_ERROR'

export const BUILD_LIST_REQUEST = 'BUILD_LIST_REQUEST'
export const BUILD_LIST_SUCCESS = 'BUILD_LIST_SUCCESS'
export const BUILD_LIST_ERROR = 'BUILD_LIST_ERROR'

export const BUILD_GET_REQUEST = 'BUILD_GET_REQUEST'
export const BUILD_GET_SUCCESS = 'BUILD_GET_SUCCESS'
export const BUILD_GET_ERROR = 'BUILD_GET_ERROR'

// WebSocket
export const SOCKET_ONOPEN = 'SOCKET_ONOPEN'
export const SOCKET_ONCLOSE = 'SOCKET_ONCLOSE'
export const SOCKET_ONERROR = 'SOCKET_ONERROR'
export const SOCKET_ONMESSAGE = 'SOCKET_ONMESSAGE'
export const SOCKET_RECONNECT = 'SOCKET_RECONNECT'
export const SOCKET_RECONNECT_ERROR = 'SOCKET_RECONNECT_ERROR'

// Auth
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR'

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR'

// Invitation
export const INVITATION_CREATE_REQUEST = 'INVITATION_CREATE_REQUEST'
export const INVITATION_CREATE_SUCCESS = 'INVITATION_CREATE_SUCCESS'
export const INVITATION_CREATE_ERROR = 'INVITATION_CREATE_ERROR'

// User
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR'
